fb_clone/fb_clone/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

fb_clone/profile_app/urls.py
from django.urls import path
from .views import profile_index, edit_profile, edit_profile_image

urlpatterns = [
    path('', profile_index, name="profile-index"),
    path('edit-profile/', edit_profile, name="edit-profile"),
    path('edit-profile-image/', edit_profile_image, name='edit-profile-image')
]

fb_clone/social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social_app.urls')),
    path('account/', include('account.urls')),
    path('friend/', include('friend_app.urls')),
    path('notification/', include('notification_app.urls')),
    path('profile/', include('profile_app.urls')),
    path('message/', include('message_app.urls')),
    path('group/', include('social_groups.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

fb_clone/account/models.py
from friend_app.models import FriendsList
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


"""
CLASS MANAGER
"""


class MyAccountManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have a username')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


def get_profile_image_filepath(self, filename):
    return f'profile_images/{self.pk}/{"profile_img"}.png'


def get_default_profile_image():
    return "default_pic/profile_image.png"


'''
ACCOUNT MODEL TABLE CLASS INHERITS AbstractBaseUser
'''


class Accounts(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(
        verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    profile_image = models.ImageField(max_length=255, upload_to=get_profile_image_filepath,
                                      null=True, blank=True, default=get_default_profile_image)
    hide_email = models.BooleanField(default=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = MyAccountManager()

    def __str__(self):
        return self.username

    def get_profile_image_filename(self):
        return str(self.profile_image)[str(self.profile_image).index('profile_images/' + str(self.pk) + "/"):]

    # For checking permissions. to keep it simple all admin have ALL permissons
    def has_perm(self, perm, obj=None):
        return self.is_admin

    # Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
    def has_module_perms(self, app_label):
        return True


@receiver(post_save, sender=Accounts)
def user_save(sender, instance, **kwargs):
    FriendsList.objects.get_or_create(user=instance)

fb_clone/profile_app/models.py
from django.db import models

# Create your models here.

fb_clone/profile_app/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.conf import settings
from account.models import Accounts
from friend_app.models import FriendsList
from django.core import files
import os
# from django.core.files.storage import FileSystemStorage
import json
import base64
from django.core.files.base import ContentFile


# Create your views here.
#TEMP_PROFILE_IMAGE_NAME = "temp_profile_image.png"


def profile_index(request):
    user = request.user
    if user.is_authenticated:
        user_id = user.id
        account = get_object_or_404(Accounts, pk=user_id)
        friend_list = FriendsList.objects.get(user=account)
        friends = friend_list.friends.all()
        context = {
            'account': account,
            'friends': friends
        }
    return render(request, 'profile_app/profile.html', context)


def edit_profile(request, *args, **kwargs):
    context = {}
    user = request.user
    if user.is_authenticated:
        user_id = user.id
        account = get_object_or_404(Accounts, pk=user_id)
        friend_list = FriendsList.objects.get(user=account)
        friends = friend_list.friends.all()
        context["account"] = account
        context["friends"] = friends
        if request.method == 'POST':
            email = request.POST.get("email")
            username = request.POST.get("username")

            account.email = email
            account.username = username
            account.save()
            return redirect("profile-index")
        else:
            print("It is not a post")
    else:
        print("User not authenticated")
    return render(request, 'profile_app/edit_profile.html', context)


def save_temp_profile_image_from_base64String(imageString):
    format, imgstr = imageString.split(';base64,')
    ext = format.split('/')[-1]
    img = base64.b64decode(imgstr)
    file_data = ContentFile(img)
    file_name = "'myphoto." + ext
    return file_name, file_data


def edit_profile_image(request):
    payload = {}
    user = request.user
    if user.is_authenticated:
        try:
            ns = json.loads(request.body)
            imageString = ns.get('image')
            file_name, file_data = save_temp_profile_image_from_base64String(
                imageString)
            user.profile_image.save(
                file_name, file_data)
            payload['result'] = "success"
        except Exception as e:
            payload["result"] = "error"
            payload["exception"] = str(e)
    return HttpResponse(json.dumps(payload), content_type="application/json")

fb_clone/profile_app/templates/profile_app/edit_profile.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}


{% block content %}
<br>
    <div class="row">
      <div class="col-3">
        {% include 'snippets/left-menu.html' %}
      </div>
      <div class="col-6">
        <h1>Edit Profile</h1>
        <div class="friend-main-image-containter">
          <img src="{{ account.profile_image.url }}" id="banner-image" class="" alt="" srcset="">
          <div class="friend-image-container" id="img-container">
              <div>
                <a href="#">
                  <img src="{{ account.profile_image.url }}" class="rounded-circle" id="mini-image" alt="" srcset="">
                  <div class="select-image-icon d-flex align-items-center">
                      <i class="fa-solid fa-camera" style="margin-left: 7px;"></i>
                  </div>
                </a>
              </div>

          </div>
      </div>
      <br>
      <br>
      <br>
      <h1>Omotosho Micheal<span style="font-size: 30px;"> ({{ account.username }})</span></h1>
      {% if friends|length == 0 or friends|length == 1 %}
          <h5>{{ friends|length }} <span style="color: gray;">friend</span></h5>
      {% else %}
          <h5>{{ friends|length }} <span style="color: gray;">friends</span></h5>
      {% endif %}
      {% if account.username == request.user.username %}
      <form action="" method="post">{% csrf_token %}
        <input class="d-none" type="file" name="profile_image" id="id_profile_image" onchange="readURL(this)">
        <div class="form-group">
            <label for="username">Username</label>
            <input class="form-control" value="{{ account.username}}" type="text" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input class="form-control" type="text" name="email" value="{{ account.email }}" id="email">
            <small class="foem-text text-muted">We'll never share your email</small>
        </div>
        <br>
        <div class="form-group">
            <button class="form-control btn btn-primary">Update Profile</button>
        </div>
        
      </form>
      
      {% endif %}
      </div>
      <div class="col-3">
        <div class="card">
            {% include 'snippets/right-data.html' %}
        </div>
      </div>
    </div>

    <script type="text/javascript">
        const img_container = document.querySelector('#img-container')
        const banner_image = document.querySelector('#banner-image')
        //const mini_image = document.querySelector('#mini-image')
        const id_profile_image = document.querySelector('#id_profile_image')
        var url = window.location.origin
        console.log(url)
        var imageFile;
	    var base64ImageString;

        function readURL(input){
		if(input.files && input.files[0]){
			var reader = new FileReader()

			reader.onload = function(e){
				var image = e.target.result
                console.log(image)
                var banner_image = document.querySelector('#banner-image')
				var imageField = document.querySelector('#mini-image')
                console.log(imageField)
				imageField.src = image
                banner_image.src = image
            

                if(image){
                    fetch(`${url}/profile/edit-profile-image/`, {
                        body: JSON.stringify({
                            image: image
                        }),
                        method: "POST",
                        headers:{
                            'X-CSRFToken': "{{csrf_token}}",
                            "Content-Type": "application/json"
                        }
                    }).then((res) => res.json()).then((data) =>{
                        console.log(data)
                    })
                }
			}

			reader.readAsDataURL(input.files[0])
		}
	}

    img_container.addEventListener('click', (e) =>{
        id_profile_image.click()
    })

    </script>
  
{% endblock %}

fb_clone/profile_app/templates/profile_app/profile.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}


{% block content %}
<br>
    <div class="row">
      <div class="col-3">
        {% include 'snippets/left-menu.html' %}
      </div>
      <div class="col-6">
        <h1>My Profile</h1>
        <div class="friend-main-image-containter">
          <img src="{{ account.profile_image.url }}" class="" alt="" srcset="">
          <div class="friend-image-container">
              <div>
                  <img src="{{ account.profile_image.url }}" class="rounded-circle" alt="" srcset="">
              </div>

          </div>
      </div>
      <br>
      <br>
      <br>
      <h1><span style="font-size: 30px;"> {{ account.username }} </span></h1>
      {% if friends|length == 0 or friends|length == 1 %}
          <h5>{{ friends|length }} <span style="color: gray;">friend</span></h5>
      {% else %}
          <h5>{{ friends|length }} <span style="color: gray;">friends</span></h5>
      {% endif %}
      {% if account.username == request.user.username %}
      <a class="btn btn-primary" href="{% url 'edit-profile' %}">Edit Profile</a>
      {% endif %}
      </div>
      <div class="col-3">
        <div class="card">
          {% include 'snippets/right-data.html' %}
        </div>
      </div>
    </div>
  
{% endblock %}